name = "thwf-podcast-prompt-queue"
main = "worker.js"
compatibility_date = "2026-04-21"

[vars]
FRONTEND_ORIGIN = "https://zdjimas.github.io"

[[kv_namespaces]]
binding = "QUEUE_KV"
id = "8a1a443956934c8e82c6b6a94e0bbb75"
